name: presence_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.8.0

dependencies: 
  get: 4.7.2
  firebase_core: 3.15.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

