name: presence_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.8.0

dependencies:
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_core: 3.15.2
  flutter:
    sdk: flutter
  get: 4.7.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/email_verified.png
    - assets/img/update_password.png
